sudo: false
language: rust

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev

rust:
  - beta
  - stable

before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

script:
  - |
      cd $TRAVIS_BUILD_DIR/monotone &&
      travis-cargo build --features=all &&
      travis-cargo test --features=all &&
      travis-cargo bench --features=all &&
      travis-cargo --only stable doc --features=all
  - |
      cd $TRAVIS_BUILD_DIR/cli &&
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo bench &&
      travis-cargo --only stable doc

env:
  global:
